// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/protobuf/Order.proto
// Protobuf Java Version: 4.28.0

package com.system.ordercontrol.protobuf;

public final class OrderProto {
  private OrderProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 0,
      /* suffix= */ "",
      OrderProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OrderItemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.OrderItem)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string product_id = 1;</code>
     * @return The productId.
     */
    java.lang.String getProductId();
    /**
     * <code>string product_id = 1;</code>
     * @return The bytes for productId.
     */
    com.google.protobuf.ByteString
        getProductIdBytes();

    /**
     * <code>int32 quantity = 2;</code>
     * @return The quantity.
     */
    int getQuantity();

    /**
     * <code>double price = 3;</code>
     * @return The price.
     */
    double getPrice();
  }
  /**
   * Protobuf type {@code protobuf.OrderItem}
   */
  public static final class OrderItem extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protobuf.OrderItem)
      OrderItemOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 0,
        /* suffix= */ "",
        OrderItem.class.getName());
    }
    // Use OrderItem.newBuilder() to construct.
    private OrderItem(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private OrderItem() {
      productId_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.system.ordercontrol.protobuf.OrderProto.internal_static_protobuf_OrderItem_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.system.ordercontrol.protobuf.OrderProto.internal_static_protobuf_OrderItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.system.ordercontrol.protobuf.OrderProto.OrderItem.class, com.system.ordercontrol.protobuf.OrderProto.OrderItem.Builder.class);
    }

    public static final int PRODUCT_ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object productId_ = "";
    /**
     * <code>string product_id = 1;</code>
     * @return The productId.
     */
    @java.lang.Override
    public java.lang.String getProductId() {
      java.lang.Object ref = productId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productId_ = s;
        return s;
      }
    }
    /**
     * <code>string product_id = 1;</code>
     * @return The bytes for productId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getProductIdBytes() {
      java.lang.Object ref = productId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int QUANTITY_FIELD_NUMBER = 2;
    private int quantity_ = 0;
    /**
     * <code>int32 quantity = 2;</code>
     * @return The quantity.
     */
    @java.lang.Override
    public int getQuantity() {
      return quantity_;
    }

    public static final int PRICE_FIELD_NUMBER = 3;
    private double price_ = 0D;
    /**
     * <code>double price = 3;</code>
     * @return The price.
     */
    @java.lang.Override
    public double getPrice() {
      return price_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(productId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, productId_);
      }
      if (quantity_ != 0) {
        output.writeInt32(2, quantity_);
      }
      if (java.lang.Double.doubleToRawLongBits(price_) != 0) {
        output.writeDouble(3, price_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(productId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, productId_);
      }
      if (quantity_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, quantity_);
      }
      if (java.lang.Double.doubleToRawLongBits(price_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, price_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.system.ordercontrol.protobuf.OrderProto.OrderItem)) {
        return super.equals(obj);
      }
      com.system.ordercontrol.protobuf.OrderProto.OrderItem other = (com.system.ordercontrol.protobuf.OrderProto.OrderItem) obj;

      if (!getProductId()
          .equals(other.getProductId())) return false;
      if (getQuantity()
          != other.getQuantity()) return false;
      if (java.lang.Double.doubleToLongBits(getPrice())
          != java.lang.Double.doubleToLongBits(
              other.getPrice())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PRODUCT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getProductId().hashCode();
      hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
      hash = (53 * hash) + getQuantity();
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getPrice()));
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.system.ordercontrol.protobuf.OrderProto.OrderItem parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.system.ordercontrol.protobuf.OrderProto.OrderItem parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.system.ordercontrol.protobuf.OrderProto.OrderItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.system.ordercontrol.protobuf.OrderProto.OrderItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.system.ordercontrol.protobuf.OrderProto.OrderItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.system.ordercontrol.protobuf.OrderProto.OrderItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.system.ordercontrol.protobuf.OrderProto.OrderItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.system.ordercontrol.protobuf.OrderProto.OrderItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.system.ordercontrol.protobuf.OrderProto.OrderItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.system.ordercontrol.protobuf.OrderProto.OrderItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.system.ordercontrol.protobuf.OrderProto.OrderItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.system.ordercontrol.protobuf.OrderProto.OrderItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.system.ordercontrol.protobuf.OrderProto.OrderItem prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.OrderItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.OrderItem)
        com.system.ordercontrol.protobuf.OrderProto.OrderItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.system.ordercontrol.protobuf.OrderProto.internal_static_protobuf_OrderItem_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.system.ordercontrol.protobuf.OrderProto.internal_static_protobuf_OrderItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.system.ordercontrol.protobuf.OrderProto.OrderItem.class, com.system.ordercontrol.protobuf.OrderProto.OrderItem.Builder.class);
      }

      // Construct using com.system.ordercontrol.protobuf.OrderProto.OrderItem.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        productId_ = "";
        quantity_ = 0;
        price_ = 0D;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.system.ordercontrol.protobuf.OrderProto.internal_static_protobuf_OrderItem_descriptor;
      }

      @java.lang.Override
      public com.system.ordercontrol.protobuf.OrderProto.OrderItem getDefaultInstanceForType() {
        return com.system.ordercontrol.protobuf.OrderProto.OrderItem.getDefaultInstance();
      }

      @java.lang.Override
      public com.system.ordercontrol.protobuf.OrderProto.OrderItem build() {
        com.system.ordercontrol.protobuf.OrderProto.OrderItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.system.ordercontrol.protobuf.OrderProto.OrderItem buildPartial() {
        com.system.ordercontrol.protobuf.OrderProto.OrderItem result = new com.system.ordercontrol.protobuf.OrderProto.OrderItem(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.system.ordercontrol.protobuf.OrderProto.OrderItem result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.productId_ = productId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.quantity_ = quantity_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.price_ = price_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.system.ordercontrol.protobuf.OrderProto.OrderItem) {
          return mergeFrom((com.system.ordercontrol.protobuf.OrderProto.OrderItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.system.ordercontrol.protobuf.OrderProto.OrderItem other) {
        if (other == com.system.ordercontrol.protobuf.OrderProto.OrderItem.getDefaultInstance()) return this;
        if (!other.getProductId().isEmpty()) {
          productId_ = other.productId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getQuantity() != 0) {
          setQuantity(other.getQuantity());
        }
        if (other.getPrice() != 0D) {
          setPrice(other.getPrice());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                productId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                quantity_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 25: {
                price_ = input.readDouble();
                bitField0_ |= 0x00000004;
                break;
              } // case 25
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object productId_ = "";
      /**
       * <code>string product_id = 1;</code>
       * @return The productId.
       */
      public java.lang.String getProductId() {
        java.lang.Object ref = productId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          productId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string product_id = 1;</code>
       * @return The bytes for productId.
       */
      public com.google.protobuf.ByteString
          getProductIdBytes() {
        java.lang.Object ref = productId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          productId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string product_id = 1;</code>
       * @param value The productId to set.
       * @return This builder for chaining.
       */
      public Builder setProductId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        productId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string product_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearProductId() {
        productId_ = getDefaultInstance().getProductId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string product_id = 1;</code>
       * @param value The bytes for productId to set.
       * @return This builder for chaining.
       */
      public Builder setProductIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        productId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int quantity_ ;
      /**
       * <code>int32 quantity = 2;</code>
       * @return The quantity.
       */
      @java.lang.Override
      public int getQuantity() {
        return quantity_;
      }
      /**
       * <code>int32 quantity = 2;</code>
       * @param value The quantity to set.
       * @return This builder for chaining.
       */
      public Builder setQuantity(int value) {

        quantity_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 quantity = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearQuantity() {
        bitField0_ = (bitField0_ & ~0x00000002);
        quantity_ = 0;
        onChanged();
        return this;
      }

      private double price_ ;
      /**
       * <code>double price = 3;</code>
       * @return The price.
       */
      @java.lang.Override
      public double getPrice() {
        return price_;
      }
      /**
       * <code>double price = 3;</code>
       * @param value The price to set.
       * @return This builder for chaining.
       */
      public Builder setPrice(double value) {

        price_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>double price = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrice() {
        bitField0_ = (bitField0_ & ~0x00000004);
        price_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.OrderItem)
    }

    // @@protoc_insertion_point(class_scope:protobuf.OrderItem)
    private static final com.system.ordercontrol.protobuf.OrderProto.OrderItem DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.system.ordercontrol.protobuf.OrderProto.OrderItem();
    }

    public static com.system.ordercontrol.protobuf.OrderProto.OrderItem getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OrderItem>
        PARSER = new com.google.protobuf.AbstractParser<OrderItem>() {
      @java.lang.Override
      public OrderItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<OrderItem> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OrderItem> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.system.ordercontrol.protobuf.OrderProto.OrderItem getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface OrderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.Order)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string customer_name = 2;</code>
     * @return The customerName.
     */
    java.lang.String getCustomerName();
    /**
     * <code>string customer_name = 2;</code>
     * @return The bytes for customerName.
     */
    com.google.protobuf.ByteString
        getCustomerNameBytes();

    /**
     * <code>string customer_email = 3;</code>
     * @return The customerEmail.
     */
    java.lang.String getCustomerEmail();
    /**
     * <code>string customer_email = 3;</code>
     * @return The bytes for customerEmail.
     */
    com.google.protobuf.ByteString
        getCustomerEmailBytes();

    /**
     * <code>string status = 4;</code>
     * @return The status.
     */
    java.lang.String getStatus();
    /**
     * <code>string status = 4;</code>
     * @return The bytes for status.
     */
    com.google.protobuf.ByteString
        getStatusBytes();

    /**
     * <code>repeated .protobuf.OrderItem order_items = 5;</code>
     */
    java.util.List<com.system.ordercontrol.protobuf.OrderProto.OrderItem> 
        getOrderItemsList();
    /**
     * <code>repeated .protobuf.OrderItem order_items = 5;</code>
     */
    com.system.ordercontrol.protobuf.OrderProto.OrderItem getOrderItems(int index);
    /**
     * <code>repeated .protobuf.OrderItem order_items = 5;</code>
     */
    int getOrderItemsCount();
    /**
     * <code>repeated .protobuf.OrderItem order_items = 5;</code>
     */
    java.util.List<? extends com.system.ordercontrol.protobuf.OrderProto.OrderItemOrBuilder> 
        getOrderItemsOrBuilderList();
    /**
     * <code>repeated .protobuf.OrderItem order_items = 5;</code>
     */
    com.system.ordercontrol.protobuf.OrderProto.OrderItemOrBuilder getOrderItemsOrBuilder(
        int index);

    /**
     * <code>.google.protobuf.Timestamp created_at = 6;</code>
     * @return Whether the createdAt field is set.
     */
    boolean hasCreatedAt();
    /**
     * <code>.google.protobuf.Timestamp created_at = 6;</code>
     * @return The createdAt.
     */
    com.google.protobuf.Timestamp getCreatedAt();
    /**
     * <code>.google.protobuf.Timestamp created_at = 6;</code>
     */
    com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder();
  }
  /**
   * Protobuf type {@code protobuf.Order}
   */
  public static final class Order extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protobuf.Order)
      OrderOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 0,
        /* suffix= */ "",
        Order.class.getName());
    }
    // Use Order.newBuilder() to construct.
    private Order(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Order() {
      id_ = "";
      customerName_ = "";
      customerEmail_ = "";
      status_ = "";
      orderItems_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.system.ordercontrol.protobuf.OrderProto.internal_static_protobuf_Order_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.system.ordercontrol.protobuf.OrderProto.internal_static_protobuf_Order_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.system.ordercontrol.protobuf.OrderProto.Order.class, com.system.ordercontrol.protobuf.OrderProto.Order.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CUSTOMER_NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object customerName_ = "";
    /**
     * <code>string customer_name = 2;</code>
     * @return The customerName.
     */
    @java.lang.Override
    public java.lang.String getCustomerName() {
      java.lang.Object ref = customerName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        customerName_ = s;
        return s;
      }
    }
    /**
     * <code>string customer_name = 2;</code>
     * @return The bytes for customerName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCustomerNameBytes() {
      java.lang.Object ref = customerName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        customerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CUSTOMER_EMAIL_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object customerEmail_ = "";
    /**
     * <code>string customer_email = 3;</code>
     * @return The customerEmail.
     */
    @java.lang.Override
    public java.lang.String getCustomerEmail() {
      java.lang.Object ref = customerEmail_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        customerEmail_ = s;
        return s;
      }
    }
    /**
     * <code>string customer_email = 3;</code>
     * @return The bytes for customerEmail.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCustomerEmailBytes() {
      java.lang.Object ref = customerEmail_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        customerEmail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object status_ = "";
    /**
     * <code>string status = 4;</code>
     * @return The status.
     */
    @java.lang.Override
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      }
    }
    /**
     * <code>string status = 4;</code>
     * @return The bytes for status.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORDER_ITEMS_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private java.util.List<com.system.ordercontrol.protobuf.OrderProto.OrderItem> orderItems_;
    /**
     * <code>repeated .protobuf.OrderItem order_items = 5;</code>
     */
    @java.lang.Override
    public java.util.List<com.system.ordercontrol.protobuf.OrderProto.OrderItem> getOrderItemsList() {
      return orderItems_;
    }
    /**
     * <code>repeated .protobuf.OrderItem order_items = 5;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.system.ordercontrol.protobuf.OrderProto.OrderItemOrBuilder> 
        getOrderItemsOrBuilderList() {
      return orderItems_;
    }
    /**
     * <code>repeated .protobuf.OrderItem order_items = 5;</code>
     */
    @java.lang.Override
    public int getOrderItemsCount() {
      return orderItems_.size();
    }
    /**
     * <code>repeated .protobuf.OrderItem order_items = 5;</code>
     */
    @java.lang.Override
    public com.system.ordercontrol.protobuf.OrderProto.OrderItem getOrderItems(int index) {
      return orderItems_.get(index);
    }
    /**
     * <code>repeated .protobuf.OrderItem order_items = 5;</code>
     */
    @java.lang.Override
    public com.system.ordercontrol.protobuf.OrderProto.OrderItemOrBuilder getOrderItemsOrBuilder(
        int index) {
      return orderItems_.get(index);
    }

    public static final int CREATED_AT_FIELD_NUMBER = 6;
    private com.google.protobuf.Timestamp createdAt_;
    /**
     * <code>.google.protobuf.Timestamp created_at = 6;</code>
     * @return Whether the createdAt field is set.
     */
    @java.lang.Override
    public boolean hasCreatedAt() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 6;</code>
     * @return The createdAt.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getCreatedAt() {
      return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 6;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
      return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(customerName_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, customerName_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(customerEmail_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, customerEmail_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(status_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, status_);
      }
      for (int i = 0; i < orderItems_.size(); i++) {
        output.writeMessage(5, orderItems_.get(i));
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(6, getCreatedAt());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(customerName_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, customerName_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(customerEmail_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, customerEmail_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(status_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, status_);
      }
      for (int i = 0; i < orderItems_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, orderItems_.get(i));
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getCreatedAt());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.system.ordercontrol.protobuf.OrderProto.Order)) {
        return super.equals(obj);
      }
      com.system.ordercontrol.protobuf.OrderProto.Order other = (com.system.ordercontrol.protobuf.OrderProto.Order) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getCustomerName()
          .equals(other.getCustomerName())) return false;
      if (!getCustomerEmail()
          .equals(other.getCustomerEmail())) return false;
      if (!getStatus()
          .equals(other.getStatus())) return false;
      if (!getOrderItemsList()
          .equals(other.getOrderItemsList())) return false;
      if (hasCreatedAt() != other.hasCreatedAt()) return false;
      if (hasCreatedAt()) {
        if (!getCreatedAt()
            .equals(other.getCreatedAt())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + CUSTOMER_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getCustomerName().hashCode();
      hash = (37 * hash) + CUSTOMER_EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getCustomerEmail().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
      if (getOrderItemsCount() > 0) {
        hash = (37 * hash) + ORDER_ITEMS_FIELD_NUMBER;
        hash = (53 * hash) + getOrderItemsList().hashCode();
      }
      if (hasCreatedAt()) {
        hash = (37 * hash) + CREATED_AT_FIELD_NUMBER;
        hash = (53 * hash) + getCreatedAt().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.system.ordercontrol.protobuf.OrderProto.Order parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.system.ordercontrol.protobuf.OrderProto.Order parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.system.ordercontrol.protobuf.OrderProto.Order parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.system.ordercontrol.protobuf.OrderProto.Order parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.system.ordercontrol.protobuf.OrderProto.Order parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.system.ordercontrol.protobuf.OrderProto.Order parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.system.ordercontrol.protobuf.OrderProto.Order parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.system.ordercontrol.protobuf.OrderProto.Order parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.system.ordercontrol.protobuf.OrderProto.Order parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.system.ordercontrol.protobuf.OrderProto.Order parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.system.ordercontrol.protobuf.OrderProto.Order parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.system.ordercontrol.protobuf.OrderProto.Order parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.system.ordercontrol.protobuf.OrderProto.Order prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.Order}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.Order)
        com.system.ordercontrol.protobuf.OrderProto.OrderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.system.ordercontrol.protobuf.OrderProto.internal_static_protobuf_Order_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.system.ordercontrol.protobuf.OrderProto.internal_static_protobuf_Order_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.system.ordercontrol.protobuf.OrderProto.Order.class, com.system.ordercontrol.protobuf.OrderProto.Order.Builder.class);
      }

      // Construct using com.system.ordercontrol.protobuf.OrderProto.Order.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getOrderItemsFieldBuilder();
          getCreatedAtFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = "";
        customerName_ = "";
        customerEmail_ = "";
        status_ = "";
        if (orderItemsBuilder_ == null) {
          orderItems_ = java.util.Collections.emptyList();
        } else {
          orderItems_ = null;
          orderItemsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        createdAt_ = null;
        if (createdAtBuilder_ != null) {
          createdAtBuilder_.dispose();
          createdAtBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.system.ordercontrol.protobuf.OrderProto.internal_static_protobuf_Order_descriptor;
      }

      @java.lang.Override
      public com.system.ordercontrol.protobuf.OrderProto.Order getDefaultInstanceForType() {
        return com.system.ordercontrol.protobuf.OrderProto.Order.getDefaultInstance();
      }

      @java.lang.Override
      public com.system.ordercontrol.protobuf.OrderProto.Order build() {
        com.system.ordercontrol.protobuf.OrderProto.Order result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.system.ordercontrol.protobuf.OrderProto.Order buildPartial() {
        com.system.ordercontrol.protobuf.OrderProto.Order result = new com.system.ordercontrol.protobuf.OrderProto.Order(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.system.ordercontrol.protobuf.OrderProto.Order result) {
        if (orderItemsBuilder_ == null) {
          if (((bitField0_ & 0x00000010) != 0)) {
            orderItems_ = java.util.Collections.unmodifiableList(orderItems_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.orderItems_ = orderItems_;
        } else {
          result.orderItems_ = orderItemsBuilder_.build();
        }
      }

      private void buildPartial0(com.system.ordercontrol.protobuf.OrderProto.Order result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.customerName_ = customerName_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.customerEmail_ = customerEmail_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.status_ = status_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.createdAt_ = createdAtBuilder_ == null
              ? createdAt_
              : createdAtBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.system.ordercontrol.protobuf.OrderProto.Order) {
          return mergeFrom((com.system.ordercontrol.protobuf.OrderProto.Order)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.system.ordercontrol.protobuf.OrderProto.Order other) {
        if (other == com.system.ordercontrol.protobuf.OrderProto.Order.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getCustomerName().isEmpty()) {
          customerName_ = other.customerName_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getCustomerEmail().isEmpty()) {
          customerEmail_ = other.customerEmail_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getStatus().isEmpty()) {
          status_ = other.status_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (orderItemsBuilder_ == null) {
          if (!other.orderItems_.isEmpty()) {
            if (orderItems_.isEmpty()) {
              orderItems_ = other.orderItems_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureOrderItemsIsMutable();
              orderItems_.addAll(other.orderItems_);
            }
            onChanged();
          }
        } else {
          if (!other.orderItems_.isEmpty()) {
            if (orderItemsBuilder_.isEmpty()) {
              orderItemsBuilder_.dispose();
              orderItemsBuilder_ = null;
              orderItems_ = other.orderItems_;
              bitField0_ = (bitField0_ & ~0x00000010);
              orderItemsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getOrderItemsFieldBuilder() : null;
            } else {
              orderItemsBuilder_.addAllMessages(other.orderItems_);
            }
          }
        }
        if (other.hasCreatedAt()) {
          mergeCreatedAt(other.getCreatedAt());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                id_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                customerName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                customerEmail_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                status_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                com.system.ordercontrol.protobuf.OrderProto.OrderItem m =
                    input.readMessage(
                        com.system.ordercontrol.protobuf.OrderProto.OrderItem.parser(),
                        extensionRegistry);
                if (orderItemsBuilder_ == null) {
                  ensureOrderItemsIsMutable();
                  orderItems_.add(m);
                } else {
                  orderItemsBuilder_.addMessage(m);
                }
                break;
              } // case 42
              case 50: {
                input.readMessage(
                    getCreatedAtFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        id_ = getDefaultInstance().getId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object customerName_ = "";
      /**
       * <code>string customer_name = 2;</code>
       * @return The customerName.
       */
      public java.lang.String getCustomerName() {
        java.lang.Object ref = customerName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          customerName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string customer_name = 2;</code>
       * @return The bytes for customerName.
       */
      public com.google.protobuf.ByteString
          getCustomerNameBytes() {
        java.lang.Object ref = customerName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          customerName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string customer_name = 2;</code>
       * @param value The customerName to set.
       * @return This builder for chaining.
       */
      public Builder setCustomerName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        customerName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string customer_name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCustomerName() {
        customerName_ = getDefaultInstance().getCustomerName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string customer_name = 2;</code>
       * @param value The bytes for customerName to set.
       * @return This builder for chaining.
       */
      public Builder setCustomerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        customerName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object customerEmail_ = "";
      /**
       * <code>string customer_email = 3;</code>
       * @return The customerEmail.
       */
      public java.lang.String getCustomerEmail() {
        java.lang.Object ref = customerEmail_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          customerEmail_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string customer_email = 3;</code>
       * @return The bytes for customerEmail.
       */
      public com.google.protobuf.ByteString
          getCustomerEmailBytes() {
        java.lang.Object ref = customerEmail_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          customerEmail_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string customer_email = 3;</code>
       * @param value The customerEmail to set.
       * @return This builder for chaining.
       */
      public Builder setCustomerEmail(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        customerEmail_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string customer_email = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCustomerEmail() {
        customerEmail_ = getDefaultInstance().getCustomerEmail();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string customer_email = 3;</code>
       * @param value The bytes for customerEmail to set.
       * @return This builder for chaining.
       */
      public Builder setCustomerEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        customerEmail_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object status_ = "";
      /**
       * <code>string status = 4;</code>
       * @return The status.
       */
      public java.lang.String getStatus() {
        java.lang.Object ref = status_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          status_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string status = 4;</code>
       * @return The bytes for status.
       */
      public com.google.protobuf.ByteString
          getStatusBytes() {
        java.lang.Object ref = status_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          status_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string status = 4;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        status_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string status = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        status_ = getDefaultInstance().getStatus();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string status = 4;</code>
       * @param value The bytes for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        status_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.util.List<com.system.ordercontrol.protobuf.OrderProto.OrderItem> orderItems_ =
        java.util.Collections.emptyList();
      private void ensureOrderItemsIsMutable() {
        if (!((bitField0_ & 0x00000010) != 0)) {
          orderItems_ = new java.util.ArrayList<com.system.ordercontrol.protobuf.OrderProto.OrderItem>(orderItems_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.system.ordercontrol.protobuf.OrderProto.OrderItem, com.system.ordercontrol.protobuf.OrderProto.OrderItem.Builder, com.system.ordercontrol.protobuf.OrderProto.OrderItemOrBuilder> orderItemsBuilder_;

      /**
       * <code>repeated .protobuf.OrderItem order_items = 5;</code>
       */
      public java.util.List<com.system.ordercontrol.protobuf.OrderProto.OrderItem> getOrderItemsList() {
        if (orderItemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(orderItems_);
        } else {
          return orderItemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protobuf.OrderItem order_items = 5;</code>
       */
      public int getOrderItemsCount() {
        if (orderItemsBuilder_ == null) {
          return orderItems_.size();
        } else {
          return orderItemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protobuf.OrderItem order_items = 5;</code>
       */
      public com.system.ordercontrol.protobuf.OrderProto.OrderItem getOrderItems(int index) {
        if (orderItemsBuilder_ == null) {
          return orderItems_.get(index);
        } else {
          return orderItemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protobuf.OrderItem order_items = 5;</code>
       */
      public Builder setOrderItems(
          int index, com.system.ordercontrol.protobuf.OrderProto.OrderItem value) {
        if (orderItemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOrderItemsIsMutable();
          orderItems_.set(index, value);
          onChanged();
        } else {
          orderItemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.OrderItem order_items = 5;</code>
       */
      public Builder setOrderItems(
          int index, com.system.ordercontrol.protobuf.OrderProto.OrderItem.Builder builderForValue) {
        if (orderItemsBuilder_ == null) {
          ensureOrderItemsIsMutable();
          orderItems_.set(index, builderForValue.build());
          onChanged();
        } else {
          orderItemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.OrderItem order_items = 5;</code>
       */
      public Builder addOrderItems(com.system.ordercontrol.protobuf.OrderProto.OrderItem value) {
        if (orderItemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOrderItemsIsMutable();
          orderItems_.add(value);
          onChanged();
        } else {
          orderItemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.OrderItem order_items = 5;</code>
       */
      public Builder addOrderItems(
          int index, com.system.ordercontrol.protobuf.OrderProto.OrderItem value) {
        if (orderItemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOrderItemsIsMutable();
          orderItems_.add(index, value);
          onChanged();
        } else {
          orderItemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.OrderItem order_items = 5;</code>
       */
      public Builder addOrderItems(
          com.system.ordercontrol.protobuf.OrderProto.OrderItem.Builder builderForValue) {
        if (orderItemsBuilder_ == null) {
          ensureOrderItemsIsMutable();
          orderItems_.add(builderForValue.build());
          onChanged();
        } else {
          orderItemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.OrderItem order_items = 5;</code>
       */
      public Builder addOrderItems(
          int index, com.system.ordercontrol.protobuf.OrderProto.OrderItem.Builder builderForValue) {
        if (orderItemsBuilder_ == null) {
          ensureOrderItemsIsMutable();
          orderItems_.add(index, builderForValue.build());
          onChanged();
        } else {
          orderItemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.OrderItem order_items = 5;</code>
       */
      public Builder addAllOrderItems(
          java.lang.Iterable<? extends com.system.ordercontrol.protobuf.OrderProto.OrderItem> values) {
        if (orderItemsBuilder_ == null) {
          ensureOrderItemsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, orderItems_);
          onChanged();
        } else {
          orderItemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.OrderItem order_items = 5;</code>
       */
      public Builder clearOrderItems() {
        if (orderItemsBuilder_ == null) {
          orderItems_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          orderItemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.OrderItem order_items = 5;</code>
       */
      public Builder removeOrderItems(int index) {
        if (orderItemsBuilder_ == null) {
          ensureOrderItemsIsMutable();
          orderItems_.remove(index);
          onChanged();
        } else {
          orderItemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.OrderItem order_items = 5;</code>
       */
      public com.system.ordercontrol.protobuf.OrderProto.OrderItem.Builder getOrderItemsBuilder(
          int index) {
        return getOrderItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protobuf.OrderItem order_items = 5;</code>
       */
      public com.system.ordercontrol.protobuf.OrderProto.OrderItemOrBuilder getOrderItemsOrBuilder(
          int index) {
        if (orderItemsBuilder_ == null) {
          return orderItems_.get(index);  } else {
          return orderItemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protobuf.OrderItem order_items = 5;</code>
       */
      public java.util.List<? extends com.system.ordercontrol.protobuf.OrderProto.OrderItemOrBuilder> 
           getOrderItemsOrBuilderList() {
        if (orderItemsBuilder_ != null) {
          return orderItemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(orderItems_);
        }
      }
      /**
       * <code>repeated .protobuf.OrderItem order_items = 5;</code>
       */
      public com.system.ordercontrol.protobuf.OrderProto.OrderItem.Builder addOrderItemsBuilder() {
        return getOrderItemsFieldBuilder().addBuilder(
            com.system.ordercontrol.protobuf.OrderProto.OrderItem.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.OrderItem order_items = 5;</code>
       */
      public com.system.ordercontrol.protobuf.OrderProto.OrderItem.Builder addOrderItemsBuilder(
          int index) {
        return getOrderItemsFieldBuilder().addBuilder(
            index, com.system.ordercontrol.protobuf.OrderProto.OrderItem.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.OrderItem order_items = 5;</code>
       */
      public java.util.List<com.system.ordercontrol.protobuf.OrderProto.OrderItem.Builder> 
           getOrderItemsBuilderList() {
        return getOrderItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.system.ordercontrol.protobuf.OrderProto.OrderItem, com.system.ordercontrol.protobuf.OrderProto.OrderItem.Builder, com.system.ordercontrol.protobuf.OrderProto.OrderItemOrBuilder> 
          getOrderItemsFieldBuilder() {
        if (orderItemsBuilder_ == null) {
          orderItemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.system.ordercontrol.protobuf.OrderProto.OrderItem, com.system.ordercontrol.protobuf.OrderProto.OrderItem.Builder, com.system.ordercontrol.protobuf.OrderProto.OrderItemOrBuilder>(
                  orderItems_,
                  ((bitField0_ & 0x00000010) != 0),
                  getParentForChildren(),
                  isClean());
          orderItems_ = null;
        }
        return orderItemsBuilder_;
      }

      private com.google.protobuf.Timestamp createdAt_;
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createdAtBuilder_;
      /**
       * <code>.google.protobuf.Timestamp created_at = 6;</code>
       * @return Whether the createdAt field is set.
       */
      public boolean hasCreatedAt() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>.google.protobuf.Timestamp created_at = 6;</code>
       * @return The createdAt.
       */
      public com.google.protobuf.Timestamp getCreatedAt() {
        if (createdAtBuilder_ == null) {
          return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
        } else {
          return createdAtBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp created_at = 6;</code>
       */
      public Builder setCreatedAt(com.google.protobuf.Timestamp value) {
        if (createdAtBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          createdAt_ = value;
        } else {
          createdAtBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp created_at = 6;</code>
       */
      public Builder setCreatedAt(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (createdAtBuilder_ == null) {
          createdAt_ = builderForValue.build();
        } else {
          createdAtBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp created_at = 6;</code>
       */
      public Builder mergeCreatedAt(com.google.protobuf.Timestamp value) {
        if (createdAtBuilder_ == null) {
          if (((bitField0_ & 0x00000020) != 0) &&
            createdAt_ != null &&
            createdAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getCreatedAtBuilder().mergeFrom(value);
          } else {
            createdAt_ = value;
          }
        } else {
          createdAtBuilder_.mergeFrom(value);
        }
        if (createdAt_ != null) {
          bitField0_ |= 0x00000020;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp created_at = 6;</code>
       */
      public Builder clearCreatedAt() {
        bitField0_ = (bitField0_ & ~0x00000020);
        createdAt_ = null;
        if (createdAtBuilder_ != null) {
          createdAtBuilder_.dispose();
          createdAtBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp created_at = 6;</code>
       */
      public com.google.protobuf.Timestamp.Builder getCreatedAtBuilder() {
        bitField0_ |= 0x00000020;
        onChanged();
        return getCreatedAtFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp created_at = 6;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
        if (createdAtBuilder_ != null) {
          return createdAtBuilder_.getMessageOrBuilder();
        } else {
          return createdAt_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp created_at = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getCreatedAtFieldBuilder() {
        if (createdAtBuilder_ == null) {
          createdAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getCreatedAt(),
                  getParentForChildren(),
                  isClean());
          createdAt_ = null;
        }
        return createdAtBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.Order)
    }

    // @@protoc_insertion_point(class_scope:protobuf.Order)
    private static final com.system.ordercontrol.protobuf.OrderProto.Order DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.system.ordercontrol.protobuf.OrderProto.Order();
    }

    public static com.system.ordercontrol.protobuf.OrderProto.Order getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Order>
        PARSER = new com.google.protobuf.AbstractParser<Order>() {
      @java.lang.Override
      public Order parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Order> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Order> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.system.ordercontrol.protobuf.OrderProto.Order getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_OrderItem_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_OrderItem_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Order_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_Order_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030src/protobuf/Order.proto\022\010protobuf\032\037go" +
      "ogle/protobuf/timestamp.proto\"@\n\tOrderIt" +
      "em\022\022\n\nproduct_id\030\001 \001(\t\022\020\n\010quantity\030\002 \001(\005" +
      "\022\r\n\005price\030\003 \001(\001\"\254\001\n\005Order\022\n\n\002id\030\001 \001(\t\022\025\n" +
      "\rcustomer_name\030\002 \001(\t\022\026\n\016customer_email\030\003" +
      " \001(\t\022\016\n\006status\030\004 \001(\t\022(\n\013order_items\030\005 \003(" +
      "\0132\023.protobuf.OrderItem\022.\n\ncreated_at\030\006 \001" +
      "(\0132\032.google.protobuf.TimestampB.\n com.sy" +
      "stem.ordercontrol.protobufB\nOrderProtob\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_protobuf_OrderItem_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_OrderItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuf_OrderItem_descriptor,
        new java.lang.String[] { "ProductId", "Quantity", "Price", });
    internal_static_protobuf_Order_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protobuf_Order_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuf_Order_descriptor,
        new java.lang.String[] { "Id", "CustomerName", "CustomerEmail", "Status", "OrderItems", "CreatedAt", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
