
INSERT INTO ingredient (name, quantity_in_stock, unity, slug) VALUES
                                                                  ('Farinha', 100.0, 'kg', 'farinha'),
                                                                  ('Açúcar', 50.0, 'kg', 'acucar'),
                                                                  ('Manteiga', 25.0, 'kg', 'manteiga'),
                                                                  ('Ovos', 200.0, 'unidades', 'ovos'),
                                                                  ('Leite', 100.0, 'litros', 'leite'),
                                                                  ('Cacau em Pó', 30.0, 'kg', 'cacau-em-po'),
                                                                  ('Extrato de Baunilha', 10.0, 'ml', 'extrato-de-baunilha'),
                                                                  ('Fermento em Pó', 15.0, 'kg', 'fermento-em-po'),
                                                                  ('Sal', 20.0, 'kg', 'sal'),
                                                                  ('Gotas de Chocolate', 50.0, 'kg', 'gotas-de-chocolate'),
                                                                  ('Creme', 30.0, 'litros', 'creme'),
                                                                  ('Morangos', 100.0, 'kg', 'morangos'),
                                                                  ('Mirtilos', 100.0, 'kg', 'mirtilos'),
                                                                  ('Bananas', 100.0, 'unidades', 'bananas'),
                                                                  ('Fermento Biológico', 10.0, 'kg', 'fermento-biologico'),
                                                                  ('Canela', 10.0, 'kg', 'canela'),
                                                                  ('Mel', 10.0, 'litros', 'mel'),
                                                                  ('Raspas de Limão', 5.0, 'kg', 'raspas-de-limao'),
                                                                  ('Amêndoas', 20.0, 'kg', 'amendoas'),
                                                                  ('Amendoim', 20.0, 'kg', 'amendoim'),
                                                                  ('Laranjas', 150.0, 'unidades', 'laranjas'),
                                                                  ('Maçãs', 120.0, 'unidades', 'macas'),
                                                                  ('Abacaxis', 30.0, 'unidades', 'abacaxis'),
                                                                  ('Uvas', 80.0, 'kg', 'uvas'),
                                                                  ('Kiwi', 60.0, 'unidades', 'kiwi'),
                                                                  ('Cenouras', 100.0, 'kg', 'cenouras'),
                                                                  ('Tomates', 200.0, 'kg', 'tomates'),
                                                                  ('Espinafre', 50.0, 'kg', 'espinafre'),
                                                                  ('Couve', 40.0, 'kg', 'couve'),
                                                                  ('Abobrinha', 60.0, 'kg', 'abobrinha'),
                                                                  ('Carne Bovina', 100.0, 'kg', 'carne-bovina'),
                                                                  ('Frango', 200.0, 'kg', 'frango'),
                                                                  ('Bacon', 50.0, 'kg', 'bacon'),
                                                                  ('Presunto', 40.0, 'kg', 'presunto'),
                                                                  ('Salsicha', 30.0, 'kg', 'salsicha'),
                                                                  ('Peito de Peru', 60.0, 'kg', 'peito-de-peru'),
                                                                  ('Linguiça', 80.0, 'kg', 'linguica'),
                                                                  ('Salmão', 20.0, 'kg', 'salmao'),
                                                                  ('Camarão', 30.0, 'kg', 'camarão'),
                                                                  ('Bacalhau', 15.0, 'kg', 'bacalhau'),
                                                                  ('Arroz', 500.0, 'kg', 'arroz'),
                                                                  ('Milho', 200.0, 'kg', 'milho'),
                                                                  ('Trigo', 300.0, 'kg', 'trigo'),
                                                                  ('Aveia', 150.0, 'kg', 'aveia'),
                                                                  ('Cevada', 100.0, 'kg', 'cevada'),
                                                                  ('Feijão Preto', 300.0, 'kg', 'feijao-preto'),
                                                                  ('Lentilha', 150.0, 'kg', 'lentilha'),
                                                                  ('Grão de Bico', 100.0, 'kg', 'grao-de-bico'),
                                                                  ('Quinoa', 50.0, 'kg', 'quinoa'),
                                                                  ('Farinha de Amêndoa', 25.0, 'kg', 'farinha-de-amendoa'),
                                                                  ('Páprica', 10.0, 'kg', 'paprica'),
                                                                  ('Pimenta-do-Reino', 15.0, 'kg', 'pimenta-do-reino'),
                                                                  ('Cravo-da-Índia', 8.0, 'kg', 'cravo-da-india'),
                                                                  ('Noz-Moscada', 6.0, 'kg', 'noz-moscada'),
                                                                  ('Gengibre em Pó', 5.0, 'kg', 'gengibre-em-po'),
                                                                  ('Açafrão', 2.0, 'kg', 'acafrao'),
                                                                  ('Cominho', 7.0, 'kg', 'cominho'),
                                                                  ('Curry', 5.0, 'kg', 'curry'),
                                                                  ('Orégano', 10.0, 'kg', 'oregano'),
                                                                  ('Pimenta Vermelha', 8.0, 'kg', 'pimenta-vermelha'),
                                                                  ('Canela em Pau', 5.0, 'kg', 'canela-em-pau'),
                                                                  ('Manjericão', 10.0, 'kg', 'manjericao'),
                                                                  ('Salsa', 10.0, 'kg', 'salsa'),
                                                                  ('Cebolinha', 10.0, 'kg', 'cebolinha'),
                                                                  ('Coentro', 10.0, 'kg', 'coentro'),
                                                                  ('Hortelã', 10.0, 'kg', 'hortela'),
                                                                  ('Tomilho', 10.0, 'kg', 'tomilho'),
                                                                  ('Alecrim', 10.0, 'kg', 'alecrim'),
                                                                  ('Louro', 10.0, 'kg', 'louro');

